app/models/User.py
from config import db
from flask_login import UserMixin

class User(db.Model, UserMixin): # UserMixin para usar o login
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True, nullable=False, unique=True)
    name = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(100), nullable=False, unique=True, name='email')
    password = db.Column(db.String(100), nullable=False)
    is_admin = db.Column(db.Boolean, default=False) # Coluna do banco de dados para verificar se o usuário é admin

    def __init__(self, name, email, password, is_admin=False): # is admin false como padrão, pois se o valor não for passado, o usuário não é admin
        self.name = name
        self.email = email
        self.password = password
        self.is_admin = is_admin

    def __repr__(self):
        return f'<User {self.name}>'







     

app/__init__.py
import os
from flask import Flask
from config import db
from config import lm
from flask_migrate import Migrate
from app.controllers.user import user_bp # importa o blueprint do usuário
from app.controllers.home import home_bp # importa o blueprint da home

def create_app():
    app = Flask(__name__)

    app.config['SECRET_KEY'] = os.getenv('SECRET_KEY')
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///database.db' # tipo de banco de dados sqlite, que criará um arquivo localmente
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False # desativa o rastreamento de modificações do SQLAlchemy - consome bastante memória quando true, pois monitoria todas as modificações no banco de dados


    db.init_app(app) # inicializa o banco de dados
    migrate = Migrate(app, db)
    migrate.init_app(app, db) # inicializa o migrate
    lm.init_app(app) # inicializa o login manager
    

    app.register_blueprint(user_bp, url_prefix='/user') # registra o blueprint do usuário
    app.register_blueprint(home_bp)

    with app.app_context():
        db.create_all() # cria todas as tabelas no banco de dados

    return app

app/controllers/home.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user

home_bp = Blueprint('home_bp', __name__)

@home_bp.route('/')
def index():
    if current_user.is_authenticated:
        return render_template('index.html')
    else:
        return redirect(url_for('user_bp.login'))

app/controllers/user.py
from flask import Blueprint, jsonify, request, render_template, redirect, url_for, flash
from app.models.User import User # importa a tabela de usuários
from config import db, lm
from flask_login import login_user, logout_user
from werkzeug.security import generate_password_hash, check_password_hash

user_bp = Blueprint('user_bp', __name__)

# user_loader
@lm.user_loader
def load_user(id):
    return User.query.get(id)

@user_bp.route('/')
def index():
    usuarios = User.query.all() # comando para pegar todos os usuários no banco de dados
    return jsonify(usuarios) # retorna todos os usuários em formato json, por enquanto

@user_bp.route('/create', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':

        data = request.form # pega os dados do usuário

        if User.query.filter_by(email=data['email']).first():
            flash('Email já cadastrado')
            return redirect(url_for('user_bp.create'))

        
        hashed_password = generate_password_hash(data['password'])
        is_admin = data.get('is_admin') == 'on' # verifica se o checkbox está de admin está marcado, se sim define como true
        user = User(name=data['name'], email=data['email'], password=hashed_password, is_admin=is_admin) # cria um novo usuário
        db.session.add(user) 
        db.session.commit() # salva as alterações no banco de dados
        login_user(user) 
        return redirect(url_for('home_bp.index'))
    else:
        return render_template('user/create.html') 

@user_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        data = request.form
        user = User.query.filter_by(email=data['email']).first()
        if user and check_password_hash(user.password, data['password']):
            login_user(user)
            return redirect(url_for('home_bp.index'))
        else:
            flash('Email ou senha incorretos')
            return redirect(url_for('user_bp.login'))
    else:
        return render_template('user/login.html')

@user_bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('home_bp.index'))

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Projeto PSI {% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    

    {% block content %}
    
    {% endblock %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block title %}
    | Home
{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="text-center mt-5">Projeto PSI</h1>
        <h2 class="mt-3">Bem-vindo, {{current_user.name}}</h2>
        <h3 class="mt-3">Informações importantes: </h3>
        <ul>
            <li>Nome: {{current_user.name}}</li>
            <li>Email: {{current_user.email}}</li>
            {% if current_user.is_admin %}
                <li>Você é um administrador</li>
            {% else %}
                <li>Você é um usuário comum</li>
            {% endif %}
        </ul>
        <a href="{{url_for('user_bp.logout')}}" class="btn btn-danger mt-3">Sair</a>
    </div>
{% endblock %}

app/templates/user/create.html
{% extends 'base.html' %}

{% block title %}
    | Criar Usuário
{% endblock %}

{% block content %}

{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-danger">{{message}} </div>
        {%endfor%}
    {%endif%}
{% endwith %}

<h1 class="text-center mt-5">Criar Usuário</h1>

<form action="{{url_for('user_bp.create')}}" method="post" class="container mt-4">
    <div class="mb-3">
        <label for="name" class="form-label">Nome:</label>
        <input type="text" name="name" placeholder="Nome" class="form-control border border-primary">
    </div>
    <div class="mb-3">
        <label for="email" class="form-label">Email:</label>
        <input type="email" name="email" placeholder="Email" class="form-control border border-primary">
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Senha:</label>
        <input type="password" name="password" placeholder="Senha" class="form-control border border-primary">
    </div>
    <div class="mb-3">
        <label for="is_admin" class="form-label">Administrador:</label>
        <input type="checkbox" name="is_admin" class="form-check-input border border-primary">
    </div>
    <button type="submit" class="btn btn-primary">Criar</button>
</form>

<p class="text-center mt-3">Já tem uma conta? <a href="{{url_for('user_bp.login')}}" class="link-primary">Login</a></p>
{% endblock %}

app/templates/user/login.html
{% extends 'base.html' %}

{% block title %}
    | Login
{% endblock %}

{% block content %}

{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-danger">{{message}} </div>
        {%endfor%}
    {%endif%}
{% endwith %}

<h1 class="text-center mt-5">Logar Usuário</h1>

<form action="{{url_for('user_bp.login')}}" method="post" class="container mt-4">
    <div class="mb-3">
        <label for="email" class="form-label">Email:</label>
        <input type="email" name="email" placeholder="Email" class="form-control border border-primary">
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Senha:</label>
        <input type="password" name="password" placeholder="Senha" class="form-control border border-primary">
    </div>
    <button type="submit" class="btn btn-primary">Logar</button>
</form>

<p class="text-center mt-3">Não tem uma conta? <a href="{{url_for('user_bp.create')}}" class="link-primary">Criar conta</a></p>
{% endblock %}